# Generated by Django 5.2 on 2025-05-14 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.estadoissue'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='prioridad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.prioridadissue'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='severidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.severidadissue'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tipoissue'),
        ),
    ]
