# Generated by Django 5.2 on 2025-05-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_issue_estado_alter_issue_prioridad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watching_issues', to='api.user'),
        ),
    ]
