# Generated by Django 5.2 on 2025-05-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_issue_watchers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='assignedTo',
        ),
        migrations.AddField(
            model_name='issue',
            name='assignedTo',
            field=models.ManyToManyField(blank=True, null=True, related_name='assigned_issues', to='api.user'),
        ),
    ]
