# Generated by Django 5.2 on 2025-05-14 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_issue_assignedto_issue_assignedto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='numIssue',
        ),
    ]
