# Generated by Django 5.2 on 2025-05-14 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_issue_numissue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assignedTo',
            field=models.ManyToManyField(blank=True, related_name='assigned_issues', to='api.user'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.estadoissue'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='prioridad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.prioridadissue'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='severidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.severidadissue'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tipoissue'),
        ),
    ]
