# Generated by Django 5.2 on 2025-05-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_issue_assignedto_alter_issue_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('selected', True)), fields=('selected',), name='unique_selected_user'),
        ),
    ]
